lib/View/privacyPolicy.dart
lib/View/terms.dart
lib/Widget/HexColor.dart
test/HexColorTest.dart

fix:利用規約とプライバシーポリシーのヘッダー部分の色を修正

---

lib/Constants/version.dart
lib/View/Setting.dart

fix: バージョンを上げた

---

document/iOS_Build.md
ios/Podfile
ios/Podfile.lock
ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata

iOSデバック周りのエラー解消

---

pubspec.yaml
test/dbInterface_test.dart

DBInterfaceのテスト追加

---

lib/View/home.dart

ロゴを表示するように修正

---

lib/View/home.dart

fix: QRのpathデータから画像を読み込むように修正

---

lib/View/home.dart
lib/View/privacyPolicy.dart

https://user-images.githubusercontent.com/45518040/125549208-d4b7717d-6aff-4c2b-a91e-1d0602edf2c7.mp4

ホーム画面の合計スタンプ数を正しく表示されるようにする

---

lib/View/Setting.dart

fix:設定画面のヘッダーだけ色が違うバグを修正

---

lib/View/Setting.dart
lib/View/history.dart

fix: ダークモード対応

---

lib/View/home.dart

スタンプ合計数の文字を中央揃えに修正

---

lib/View/Setting.dart

スタンプを交換する際の個数を明示

---

lib/View/Setting.dart
lib/View/home.dart
lib/dbHelper.dart
lib/dbInterface.dart
lib/models/stamp.dart

スタンプテーブルのカラム修正

---

lib/Widget/stampDialog.dart

imageという文字を消す

---

lib/View/home.dart
pubspec.yaml

文字のフォントを変更
背景を追加
合計スタンプ数の位置の変更

ホーム画面のデザインを更新

---

lib/View/home.dart

スタンプ利用後のスタンプシートが更新されない不具合及びスタンプ合計数の不具合を修正

fix:スタンプ利用後のスタンプシートが更新されない不具合を修正

---

lib/View/Setting.dart
lib/Widget/stampDialog.dart
lib/l10n/app_en.arb
lib/l10n/app_ja.arb

i18n対応抜けを修正しました。
一通り確認して他に修正する場所はなかったと思いますが、あればレビューしてください。

fix:i18n対応抜け修正

---

lib/View/qrScan.dart

clean:qrScan.dartのリファクタリング

---

lib/View/history.dart

履歴削除ボタンを配置

---

lib/View/home.dart

スタンプダイアログでスタンプ情報読み込み時不正な値が入る問題解消

---

lib/View/Setting.dart

スタンプ消費のさい使用したスタンプ履歴が全部でるのを一個で済むように

---

lib/Util/toDateOrTime.dart
lib/View/Setting.dart
lib/Widget/stampDialog.dart

スタンプ使用した際にIDが表示されるのを日付にする

---

lib/View/history.dart

fix:スタンプ履歴画面のマージンを調整する

---

lib/dbHelper.dart
lib/dbInterface.dart

clean: DB周りのdocを追加

---

lib/View/README.md

add:ViewのREADME作成 #231 

---

lib/Util/README.md
lib/Widget/README.md

UtilのREADME作成

---

lib/dbInterface.dart

/lib/dbInterface.dartのselectStampCountは「deleteflgがfalseのスタンプ数を取得する」だけどselectDeleteFlgだと「deleteFlgが0のスタンプを取得する」になってるのでfalseに統一しました

/lib/dbInterface.dartの文面統一
